# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty-ubuntu-64"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vmwarefusion.box"


  config.vm.network :forwarded_port, guest: 80, host: 4000

  # config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.network :public_network

  # config.ssh.forward_agent = true

  config.vm.synced_folder "../", "/var/www/"

  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end

  # config.vm.provision :shell, :inline => "apt-get update --fix-missing && apt-get -y install puppet"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file  = "system.pp"
    puppet.module_path    = "puppet_modules"
    puppet.options        = "--verbose --debug"
  end
end
